<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CETCompat>false</CETCompat>
    <RootNamespace>MikuSB.MikuSB</RootNamespace>
    <AssemblyName>MikuSB</AssemblyName>
    <ApplicationIcon>Source\Snowbreak.ico</ApplicationIcon>
	<SatelliteResourceLanguages>false</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\GameServer\GameServer.csproj" />
    <ProjectReference Include="..\SdkServer\SdkServer.csproj" />
  </ItemGroup>

</Project>
